package Daily.Easy;

/*

389. Find the Difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

 */

import java.util.HashSet;
import java.util.Set;

public class Q389_Find_the_Difference {
    public static char findTheDifference(String s, String t) {
        if (t.length() <= s.length()) {
            return '0';
        }
        int sum = 0;
        for (char c : t.toCharArray()) {
            sum += (c - 'a');
        }
        System.out.println("Sum=" + sum);
        for (char c : s.toCharArray()) {
            sum -= (c - 'a');
        }
        System.out.println("Sum=" + sum);
        return (char) (sum + 'a');
    }
}
